//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChefBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChefBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.codechef.com/problems/TWOSTR
        ///https://www.codechef.com/problems/CHRL4
        ///https://www.codechef.com/problems/COOKMACH
        ///https://www.codechef.com/problems/FLOW015
        ///https://www.codechef.com/problems/CHEFSQ
        ///https://www.codechef.com/problems/MISSP
        ///https://www.codechef.com/problems/RECTSQ
        ///https://www.codechef.com/problems/FLOW014
        ///https://www.codechef.com/problems/FLOW010
        ///https://www.codechef.com/problems/FLOW011
        ///https://www.codechef.com/problems/FLOW016
        ///https://www.codechef.com/problems/PALL01
        ///https://www.cod [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.codechef.com/problems/MX
        ///https://www.codechef.com/problems/SCLUSTER
        ///https://www.codechef.com/problems/TMBOX
        ///https://www.codechef.com/problems/L2GRAPH
        ///https://www.codechef.com/problems/SEADIVM
        ///https://www.codechef.com/problems/BICKER
        ///https://www.codechef.com/problems/AMBIDEX
        ///https://www.codechef.com/problems/SIMNIM
        ///https://www.codechef.com/problems/CHECKERS
        ///https://www.codechef.com/problems/CX
        ///https://www.codechef.com/problems/EX
        ///https://www.codechef.com/problems/ALLINONE
        ///https://www.codechef.com [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Challenge {
            get {
                return ResourceManager.GetString("Challenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.codechef.com/problems/DCGAME
        ///https://www.codechef.com/problems/OMAX
        ///https://www.codechef.com/problems/AEHASH
        ///https://www.codechef.com/problems/GERALD05
        ///https://www.codechef.com/problems/NDUNGEON
        ///https://www.codechef.com/problems/PRIMPATT
        ///https://www.codechef.com/problems/CIRCUITS
        ///https://www.codechef.com/problems/FIRE
        ///https://www.codechef.com/problems/BYTEISLE
        ///https://www.codechef.com/problems/FLUSHOT
        ///https://www.codechef.com/problems/WINDOW2
        ///https://www.codechef.com/problems/CPOINT
        ///https://www. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.codechef.com/problems/HOLIDAY1
        ///https://www.codechef.com/problems/INSOMB5
        ///https://www.codechef.com/problems/INSOMB7
        ///https://www.codechef.com/problems/AXR1P1
        ///https://www.codechef.com/problems/AXR1P4
        ///https://www.codechef.com/problems/AXR2P1
        ///https://www.codechef.com/problems/AXR2P3
        ///https://www.codechef.com/problems/AXR2P4
        ///https://www.codechef.com/problems/MANIP1
        ///https://www.codechef.com/problems/MANIP5
        ///https://www.codechef.com/problems/MANIP6
        ///https://www.codechef.com/problems/CREDE1
        ///https://www.code [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Extcontest {
            get {
                return ResourceManager.GetString("Extcontest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://c.happycodings.com/c-on-unix/code1.html
        ///http://c.happycodings.com/c-on-unix/code2.html
        ///http://c.happycodings.com/c-on-unix/code3.html
        ///http://c.happycodings.com/c-on-unix/code4.html
        ///http://c.happycodings.com/c-on-unix/code5.html
        ///http://c.happycodings.com/c-on-unix/code6.html
        ///http://c.happycodings.com/c-on-unix/code7.html
        ///http://c.happycodings.com/c-on-unix/code8.html
        ///http://c.happycodings.com/c-on-unix/code9.html
        ///http://c.happycodings.com/c-on-unix/code10.html
        ///http://c.happycodings.com/c-on-unix/code1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FakeSC {
            get {
                return ResourceManager.GetString("FakeSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.codechef.com/problems/POST
        ///https://www.codechef.com/problems/ACMKANPA
        ///https://www.codechef.com/problems/CLOWAY
        ///https://www.codechef.com/problems/DUALPAL
        ///https://www.codechef.com/problems/ARCHPLG
        ///https://www.codechef.com/problems/QSTRING
        ///https://www.codechef.com/problems/CONPOIN
        ///https://www.codechef.com/problems/DISTNUM
        ///https://www.codechef.com/problems/HAMILG
        ///https://www.codechef.com/problems/CHEFBOOK
        ///https://www.codechef.com/problems/HYPER
        ///https://www.codechef.com/problems/CIELWEB
        ///https://www.c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.codechef.com/problems/CHEFPRES
        ///https://www.codechef.com/problems/CARDLINE
        ///https://www.codechef.com/problems/E2
        ///https://www.codechef.com/problems/SEQLCS
        ///https://www.codechef.com/problems/AGENTS
        ///https://www.codechef.com/problems/CUTSQRS
        ///https://www.codechef.com/problems/PHRASES
        ///https://www.codechef.com/problems/MENU
        ///https://www.codechef.com/problems/G2
        ///https://www.codechef.com/problems/SWARM
        ///https://www.codechef.com/problems/ECODE
        ///https://www.codechef.com/problems/GRIDCHEF
        ///https://www.codechef.com [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.codechef.com/problems/TWOSTR
        ///https://www.codechef.com/problems/CHRL4
        ///https://www.codechef.com/problems/COOKMACH
        ///https://www.codechef.com/problems/FLOW015
        ///https://www.codechef.com/problems/CHEFSQ
        ///https://www.codechef.com/problems/MISSP
        ///https://www.codechef.com/problems/RECTSQ
        ///https://www.codechef.com/problems/FLOW014
        ///https://www.codechef.com/problems/FLOW010
        ///https://www.codechef.com/problems/FLOW011
        ///https://www.codechef.com/problems/FLOW016
        ///https://www.codechef.com/problems/PALL01
        ///https://www.cod [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string School {
            get {
                return ResourceManager.GetString("School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36.
        /// </summary>
        internal static string UserAgent {
            get {
                return ResourceManager.GetString("UserAgent", resourceCulture);
            }
        }
    }
}
